version: '3.9'
services:
  loki:
    image: grafana/loki:2.9.2
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./observability/loki-config.yml:/etc/loki/config.yml
    ports:
      - '3100:3100'

  promtail:
    image: grafana/promtail:2.9.2
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./observability/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
      - ./logs:/var/log/yseeku
    depends_on:
      - loki
