global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['host.docker.internal:3001']
    metrics_path: /api
rule_files:
  - /etc/prometheus/alerts.yml
